🚲 Cycle candidates
Joystream/pioneer pull request #1584
Opened 2021-10-04 12:31 UTC by p-sad

See #1388 
Potentially closes this issue; I'm not sure though, because I don't really understand what "preview mode" is.

2021-10-04 15:59 UTC, jodator requested changes
Works nice :) But I think that we could add tests for cycling.

ps.: Please add an issue for handling the "forum thread" button.

2021-10-04 15:59 UTC, jodator commented on packages/ui/src/council/modals/CandidacyPreview/CandidacyPreview.tsx
> +  const onClickRight = () => candidates && isDefined(candidateIndex) && setCandidateId(candidates[candidateIndex + 1])
Let's have a simple test for this modal:

*   Just 3 candidates
*   check states on first, last, and that left/right clicks changes candidate

2021-10-05 11:04 UTC, p-sad commented on packages/ui/src/council/modals/CandidacyPreview/CandidacyPreview.tsx
> +            textToCopy={`${window.location.host}/#/members/${candidate?.member.id}`}
I haven't found any issue that relates to this, and I think it might deserve its own issue. I think link to member preview had one.

2021-10-05 12:54 UTC, jodator reviewed
LGTM, but some finishing touches would be nice 👍

2021-10-05 12:54 UTC, jodator commented on packages/ui/test/council/modals/CandidacyPreview.test.tsx
> +    ;['0', '1'].map((id) =>
Let's use `.forEach()` instead of `.map`

2021-10-05 12:54 UTC, jodator commented on packages/ui/src/council/modals/CandidacyPreview/CandidacyPreview.tsx
> +const ArrowLeftIcon = () => (
Maybe move that to icons?

2021-10-05 12:54 UTC, jodator commented on packages/ui/src/council/modals/CandidacyPreview/CandidacyPreview.tsx
> +            textToCopy={`${window.location.host}/#/members/${candidate?.member.id}`}
So let's create a separate issue for handling links to candidates.

2021-10-05 12:54 UTC, jodator commented on packages/ui/src/council/modals/CandidacyPreview/CandidacyPreview.tsx
> +              candidateIndex === candidates.length - 1
Maybe something like this:

```typescript
disabled={isNextDisabled(candidateIndex, candidates)}
```

2021-10-05 14:25 UTC, p-sad commented on packages/ui/src/council/modals/CandidacyPreview/CandidacyPreview.tsx
> +            textToCopy={`${window.location.host}/#/members/${candidate?.member.id}`}
Added #1590

2021-10-05 17:00 UTC, p-sad commented
Closing because a github outage prevents the last 3 commits from showing up in the PR

2021-10-05 17:00 UTC, closed without merging