🌍  BountyListItem
Joystream/pioneer pull request #1981
Opened 2021-12-14 14:28 UTC by WRadoslaw

closes #1968

2021-12-14 16:46 UTC, RafalPloszka commented on packages/ui/src/bounty/types/Bounty.ts
> +export type BountyPeriod = 'funding' | 'working' | 'judgment' | 'withdrawal' | 'expired'
Typo:
```suggestion
export type BountyPeriod = 'funding' | 'working' | 'judgement' | 'withdrawal' | 'expired'
```

2021-12-16 10:53 UTC, stepien4soft approved these changes

2021-12-16 12:28 UTC, Qcza requested changes

2021-12-16 12:28 UTC, Qcza commented on packages/ui/src/bounty/components/BountyListItem/components/DetailBox.tsx
> +  children: React.ReactNode | string | number
I believe ReactNode already covers "string" and "number".``
```suggestion
  children: React.ReactNode
```

2021-12-16 13:44 UTC, Qcza approved these changes

2021-12-16 13:48 UTC, merged