🌞  Bounty top contributors
Joystream/pioneer pull request #1997
Opened 2021-12-16 13:43 UTC by WRadoslaw

2021-12-16 14:05 UTC, Qcza requested changes

2021-12-16 14:05 UTC, Qcza commented on packages/ui/src/common/components/HorizontalScroller/HorizontalScroller.tsx
> +    wrapperRef.current.scrollBy({ left: scrollNumber, behavior: 'smooth' })
```suggestion
    wrapperRef.current?.scrollBy({ left: scrollNumber, behavior: 'smooth' })
```

2021-12-16 14:05 UTC, Qcza commented on packages/ui/src/common/components/HorizontalScroller/HorizontalScroller.tsx
> +    wrapperRef.current.scrollBy({ left: scrollNumber * -1, behavior: 'smooth' })
```suggestion
    wrapperRef.current?.scrollBy({ left: scrollNumber * -1, behavior: 'smooth' })
```

2021-12-16 14:05 UTC, Qcza commented on packages/ui/src/common/components/HorizontalScroller/HorizontalScroller.tsx
> +    const childrenWidth = wrapperRef.current?.children[0]?.clientWidth + 16
```suggestion
    const childrenWidth = (wrapperRef.current?.children[0]?.clientWidth ?? 0) + 16
```

2021-12-16 14:26 UTC, stepien4soft approved these changes

2021-12-17 06:29 UTC, Qcza approved these changes

2021-12-17 07:54 UTC, merged