Feature/bounties my tabs
Joystream/pioneer pull request #2093
Opened 2022-01-17 14:22 UTC by WRadoslaw

2022-01-18 13:35 UTC, Qcza requested changes

2022-01-18 13:35 UTC, Qcza commented on packages/ui/src/app/pages/Bounty/components/BountiesLayout.tsx
> +            {tilesComponent || null}
```suggestion
            {tilesComponent}
```

2022-01-18 13:35 UTC, Qcza commented on packages/ui/src/app/pages/Bounty/components/BountiesLayout.tsx
> +  noMember = false,
There is no need to declare defaults here as undefined will be handled the same as boolean.
```suggestion
  noMember,
```

2022-01-19 08:30 UTC, RafalPloszka approved these changes

2022-01-19 11:39 UTC, Qcza approved these changes

2022-01-19 12:36 UTC, merged