Bounty page components
Joystream/pioneer pull request #2120
Opened 2022-01-21 07:54 UTC by RafalPloszka

Closes #1956

2022-01-24 12:40 UTC, RafalPloszka commented
:warning:  Important note for code review
I made some rearrangements in files/directories structure, I describe them here for easier code review:

1.  New directory `bounty/components/BountyMainComponents`.
Components with the main part of bounty page according to its stage. `BountyExpired` and `BountyFailed` were moved there and I added corresponding components for other stages.

2.  New directory `bounty/components/tabsSets`:
`ResultsTabs` for bounties in Failed and Succesful stages, `CommonTabs` for the rest.
(`ExpiredTabs` was deleted and now `CommonTabs` is used instead. `FailedTabs` was deleted and now `ResultsTabs` is used instead.)

3.  New directory `bounty/components/BountyTiles`:
`FundingTiles` for Funding stage, `ResultsTiles` for Failed/Successful stage, `CommonTiles` for the rest.
(`ExpiredTiles` was deleted and now `CommonTiles` is used instead. `FailedTiles` was deleted and now `ResultsTiles` is used instead.)

4. New directory `bounty/components/modalsButtons`:
Buttons for calling buttons. `AddBountyModalButton`, `SubmitWorkButton` and 'WithdrawStakeButton` were moved here and I added buttons for calling the rest of bounties modals

2022-01-24 15:29 UTC, Qcza requested changes
Please apply `React.memo` to components that receive props.

2022-01-24 15:29 UTC, Qcza commented on packages/ui/src/bounty/components/BountyMainComponents/BountyFunding.tsx
> +              periodsLengths={{
Move this object to `useMemo`.

2022-01-24 15:29 UTC, Qcza commented on packages/ui/src/bounty/components/BountyMainComponents/BountyJudgement.tsx
> +              periodsLengths={{
Move this object to `useMemo`

2022-01-24 15:29 UTC, Qcza commented on packages/ui/src/bounty/components/BountyMainComponents/BountyWorking.tsx
>                periodsLengths={{
Move it to `useMemo`

2022-01-24 15:29 UTC, Qcza commented on packages/ui/src/bounty/components/BountyPreviewHeader/BountyPreviewHeader.tsx
> +import BN from 'bn.js'
Apply `React.memo` to all components in this file.

2022-01-24 15:29 UTC, Qcza commented on packages/ui/src/bounty/components/BountyMainComponents/BountyExpired.tsx
>                periodsLengths={{
Move it to `useMemo`

2022-01-24 15:29 UTC, Qcza commented on packages/ui/src/bounty/components/BountyPreviewHeader/BountyPreviewHeader.tsx
> +      {winnerConditions && <ClaimRewardButton bountyId={bounty.id} entryId={entryId} reward={new BN(reward)} />}
Do not call the constructor in the component prop if the component you pass this prop to uses `React.memo`.

2022-01-25 06:49 UTC, Qcza approved these changes

2022-01-25 07:51 UTC, merged