👁 Bugfix/404 response for election tab
Joystream/pioneer pull request #2360
Opened 2022-02-28 14:08 UTC by stepien4soft

Close #2319

2022-03-04 13:23 UTC, thesan requested changes
Fixing the `electionLink` solves a lot of the issue, but the blank page on `/#/election/` and `/#/election/my-votes` once the election ends is also part of it.
It could be handled with something like:
```ts
history.replace({ pathname: ElectionRoutes.pastElections })
```

Also I don't understand why replacing "There are no candidates yet" by "There is no election now", isn't this showing when there is no candidates ?

2022-03-04 13:47 UTC, thesan commented
I've added a way to test the `idle` stage for as long as you want.
If you need this run:
1. `docker-compose run --rm build`
2. `yarn workspace ui helpers setChainSpec -s idle -d 1000` (now the chain spec will keep the council idle for 1000 block)
3. `docker-compose up node`

From there you should be able to work with the council `idle` for 100 minutes, when using the `local-mocks` network.

More info in [docs/mocks.md](https://github.com/Joystream/pioneer/blob/5d1dee7808e4b2a665775fb2b8a75cf7af0f0bd1/docs/mocks.md)

2022-03-07 15:15 UTC, thesan commented on packages/ui/src/app/pages/Election/Election.tsx
I meant something like:
```ts
useEffect(() => {
 if (electionStage === 'inactive') {
    history.replace(ElectionRoutes.pastElections)
  }
}, [electionStage])
```

2022-03-11 09:03 UTC, dmtrjsg commented
Merge Olympia branch into this branch @stepien4soft 
@thesan  to test.

2022-03-16 11:32 UTC, thesan commented on packages/ui/test/council/components/ElectionTabs.test.tsx
> +      stubCouncilAndReferendum(api, 'Announcing', 'Inactive')
@stepien4soft IMO councilStage: 'Election' and electionStage: 'Inactive' still means "inactive stage" (also I don't think it should happen). If this looks right to you please merge the PR :champagne:

2022-03-16 14:19 UTC, merged