Fix on withdraw contribution modal
Joystream/pioneer pull request #2551
Opened 2022-03-14 15:36 UTC by WRadoslaw

2022-03-16 12:58 UTC, thesan requested changes
Thanks for the PR, I just found a few problems most of them related to the previous logic

2022-03-16 12:58 UTC, thesan commented on packages/ui/src/bounty/modals/SubmitWorkModal/SubmitWorkModal.tsx
> +    }
Nice catch! But we shouldn't have side effects in `useMemo`, please move the `hideModal()` in a `useEffect` (and I guess `modalData.bounty?.entries?.find((...` in a diferent `useMemo`)

2022-03-16 12:58 UTC, thesan commented on packages/ui/src/bounty/components/BountyPreviewHeader/BountyPreviewHeader.tsx
>      return null
This: `isTerminated = !bounty.isTerminated ...` is kind of confusing :raised_eyebrow: 
What about ?
```suggestion
  if (bounty.isTerminated || !hasAnnounced && !isContributor) {
    return null
```

2022-03-16 12:58 UTC, thesan commented on packages/ui/src/bounty/components/BountyPreviewHeader/BountyPreviewHeader.tsx
>        ) : (
I don't think `<WithdrawContributionButton />` should show at all during the successful stage

2022-03-18 11:28 UTC, thesan commented on packages/ui/src/bounty/queries/bounty.graphql
> +}
Sorry about the confusion when I suggested to check the withdrawal event I just meant to add:
```gql
withdrawnInEvent { __typename }
```
in the existing:  [`fragment BountyContributionFields`](https://github.com/Joystream/pioneer/blob/78d6521e4550c1b1813e6004f2af6a459d78d075/packages/ui/src/bounty/queries/bounty.graphql#L82)

This way you can add a `isWithdrawy: !!field.asContributor` in [@/bounty/types/casts](https://github.com/Joystream/pioneer/blob/78d6521e4550c1b1813e6004f2af6a459d78d075/packages/ui/src/bounty/types/casts.ts#L83) and there's no need for an extra query, and adding an extra hook to the codebase.

2022-03-21 09:19 UTC, dmtrjsg commented
Add cases for cherry and Funding expired.

In case Funding Expires (zero contributions), the cherry needs to be returned to creator upon withdrawing
In case there's one contributor, cherry goes to that user in full (if bounty fails, nothing returned to creator)

2022-03-21 09:25 UTC, dmtrjsg commented
When you create bounty, it creates bounty and dispatches fe event, that is just a cherry, but that is treated as contribution.

Cherry < > Bounty contribution

2022-03-21 10:21 UTC, thesan approved these changes

2022-03-21 11:10 UTC, merged