🦺 Refactor on Add bounty modal
Joystream/pioneer pull request #2775
Opened 2022-04-04 08:31 UTC by WRadoslaw

2022-04-04 09:16 UTC, WRadoslaw commented on packages/ui/src/bounty/modals/AddBountyModal/helpers.ts
> +    fundingMaximalRange: Yup.number().min(1, 'Value must be greater than zero').required(''),
Both ranges should be BN

2022-04-05 09:57 UTC, stepien4soft approved these changes

2022-04-05 12:05 UTC, thesan requested changes
Impressive PR :muscle: . I'm glad the other modals are split into others !

Would just like to clarify the validation logic a bit

2022-04-06 07:47 UTC, thesan approved these changes
Thanks

2022-04-06 09:28 UTC, merged