Refactor of announce entry validation
Joystream/pioneer pull request #2778
Opened 2022-04-04 10:15 UTC by WRadoslaw

2022-04-06 13:37 UTC, thesan requested changes
Looks good ! There's a detail about the context types, but mostly it looks like `@/memberships/model/validation` has duplicated logic. Did you rename this file in  #2775 ?

2022-04-06 13:37 UTC, thesan commented on packages/ui/src/bounty/modals/AnnounceWorkEntryModal/machine.ts
> +type AnnounceWorkEntryContext = Partial<ContributionContext & TransactionContext>
AFAICS one of these types is redundant. Why not:
```suggestion
interface ContributionContext {
  stakingAccount?: Account
}

interface TransactionContext extends ContributionContext {
  transactionEvents?: EventRecord[]
}
```
And later:
```ts
  | { value: AnnounceWorkEntryStates.contribute; context: Reqired<ContributionContext> }
```

2022-04-07 08:44 UTC, WRadoslaw commented
> Looks good ! There's a detail about the context types, but mostly it looks like `@/memberships/model/validation` has duplicated logic. Did you rename this file in #2775 ?

Yeah, seems like merge/rebase issue

2022-04-08 10:31 UTC, thesan approved these changes
LGTM !

2022-04-08 11:39 UTC, merged