Show correct stake required for the WG Opening.
Joystream/pioneer pull request #2903
Opened 2022-04-24 21:51 UTC by oleksanderkorn

https://github.com/Joystream/pioneer/issues/2394
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/9252017/164998136-50decf18-a48b-475f-895d-0ff92f9eae25.png">

2022-04-25 21:13 UTC, singulart approved these changes

2022-04-26 15:08 UTC, thesan requested changes
Thank you for the PR. This is most of what was needed. But as @dmtrjsg requested [here](https://github.com/Joystream/pioneer/issues/2394#issuecomment-1108404003) could you please also pre-populate the stake input with the required stake (ATM it's only a placeholder):

![Screenshot from 2022-04-26 17-06-36](https://user-images.githubusercontent.com/6571453/165332186-66a929bc-a0c4-4038-8c39-baa5a79cc3b8.png)

2022-04-26 17:11 UTC, oleksanderkorn commented
> Thank you for the PR. This is most of what was needed. But as @dmtrjsg requested [here](https://github.com/Joystream/pioneer/issues/2394#issuecomment-1108404003) could you please also pre-populate the stake input with the required stake (ATM it's only a placeholder):
> 
> ![Screenshot from 2022-04-26 17-06-36](https://user-images.githubusercontent.com/6571453/165332186-66a929bc-a0c4-4038-8c39-baa5a79cc3b8.png)

@thesan i have added pre-poluation of the stake to minimum stake.

2022-04-27 09:29 UTC, thesan approved these changes
Perfect :100:

2022-04-27 09:32 UTC, merged