Made Become-A-Member header as sticky
Joystream/pioneer pull request #2958
Opened 2022-05-03 12:56 UTC by talentdev0807

This bug comes from adding Become a member header
Originally, main body height is 100%, it is natural to have scroll when we add it on top screen
So, I made Become a member header as sticky header

2022-05-03 13:12 UTC, singulart commented
Fixes https://github.com/Joystream/pioneer/pull/2958

2022-05-03 13:12 UTC, singulart commented
Fixes https://github.com/Joystream/pioneer/issues/2689

2022-05-10 07:37 UTC, stepien4soft commented on packages/ui/src/app/components/OnboardingOverlay/OnBoardingOverlay.tsx
> +  width: 100%;
Hi @talentdev0807, First of all thank you for this PR. Just one small fix has to be added - for now <ButtonPrimary>Join now </ButtonPrimary> isn’t visible. Two quick solution is to change width for a main wrapper or set up padding on Join now button

2022-05-10 07:40 UTC, stepien4soft requested changes
Hi @talentdev0807, First of all thank you for this PR. Just one small fix has to be added - for now <ButtonPrimary>Join now </ButtonPrimary> isn’t visible. Two quick solution is to change width for a main wrapper or set up padding on Join now button

2022-05-11 08:24 UTC, stepien4soft commented
Approved! Thanks for that

2022-05-11 08:24 UTC, stepien4soft approved these changes

2022-05-11 08:25 UTC, merged