Prev step button added for applying
Joystream/pioneer pull request #3118
Opened 2022-05-28 11:35 UTC by ytdbuolf

Prev-step button has been added to opening application flow
Issue #2445 has been fixed now

2022-06-01 16:32 UTC, thesan requested changes
Thank you for the PR. See the CR below

2022-06-16 19:19 UTC, freakstatic commented on packages/ui/src/working-groups/modals/ApplyForRoleModal/ApplyForRoleModal.tsx
> +        </ButtonPrev>
@thesan it seems that @ytdbuolf was gone MIA go I apply your suggestion on this `[PR](https://github.com/Joystream/pioneer/pull/3249)`

2022-06-20 18:15 UTC, thesan commented
Done by #3249

2022-06-20 18:15 UTC, thesan commented
Done by #3249

2022-06-20 18:15 UTC, closed without merging