Update for staking amount validate
Joystream/pioneer pull request #3193
Opened 2022-06-06 14:36 UTC by Ken-tech-max

2022-06-09 09:36 UTC, WRadoslaw requested changes
Hello! Since whole validation was transferred to React Hook Form, there is no need to additionally keep it in `useState`. This issue can be resolved by only changing error message inside AddNewProposalModal `schemaFactory` function. Validation is working correctly (returns valid when value is equal), so message is only thing tthat's need to be changed.

2022-06-09 09:36 UTC, WRadoslaw commented on packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/WorkingGroupLeadOpening/CreateWorkingGroupLeadOpening/StakingPolicyAndReward.tsx
> +  const maxAllowedForStakingAmount = 200
This validation must be based on node constant

2022-06-10 14:31 UTC, Ken-tech-max commented
Fixed : 3091

2022-06-22 06:15 UTC, Ken-tech-max commented
Updated issue 2770

2022-07-20 06:41 UTC, singulart commented
@Ken-tech-max Any updates on this?

2022-07-20 07:16 UTC, Ken-tech-max commented
I am working on it
Just started right now

2022-08-19 08:18 UTC, dmtrjsg commented
@singulart is it possible to clarify which issues exactly were fixed with this PR? Possible to commit them separately?

cc @thesan

2022-08-19 08:57 UTC, singulart commented
The worker doesn't respond, it's not realistic to extract the info requested...

2022-08-19 11:16 UTC, thesan approved these changes

2022-08-19 11:40 UTC, WRadoslaw approved these changes

2022-08-19 11:42 UTC, merged