🌟 Accounts lock info optimisation
Joystream/pioneer pull request #3267
Opened 2022-06-20 19:24 UTC by RafalPloszka

Closes #3238

2022-06-24 06:48 UTC, RafalPloszka commented on packages/ui/src/accounts/modals/MoveFoundsModal/MoveFundsModalButtons.tsx
>    }
An extension cannot be opened programmatically
[https://stackoverflow.com/questions/10479679/how-can-i-open-my-extensions-pop-up-with-javascrip](https://stackoverflow.com/questions/10479679/how-can-i-open-my-extensions-pop-up-with-javascript)

2022-06-24 10:45 UTC, stepien4soft commented
![Screenshot 2022-06-24 at 12 41 46](https://user-images.githubusercontent.com/75029057/175519155-246e6e8a-88e2-4c9f-92e7-0e50e666e79c.png)

Styles have to be improved. Also links inside tooltip doesn't work (dropdown is hiding instead redirect user to the correct page)

2022-06-28 09:48 UTC, stepien4soft requested changes

2022-06-28 09:48 UTC, stepien4soft commented on packages/ui/src/accounts/components/SelectAccount/SelectAccount.tsx
> +    }, [filteredOptions, search, selected])
Is it possible to simplify this?

2022-06-28 09:48 UTC, stepien4soft commented on packages/ui/src/common/components/selects/components.tsx
> +        /* opacity: 0.6; */
it should be deleted or uncomment

2022-06-28 09:48 UTC, stepien4soft commented on packages/ui/src/common/components/selects/select.tsx
> +      // TODO: figure out a way to enable clicking on the links in Tooltips
i hope it coul help (check for example - StakingAccountStep.tsx file). There exist tooltip with link

2022-06-28 09:48 UTC, stepien4soft commented on packages/ui/src/council/modals/AnnounceCandidacy/AnnounceCandidacyModal.tsx
>      constants?.election.minCandidacyStake.toNumber() || 0,
After tJoy refactor minCandidacyStake should be BN

2022-06-28 09:48 UTC, stepien4soft commented on packages/ui/src/council/modals/VoteForCouncil/VoteForCouncilModal.tsx
> +  const requiredStake = minStake as BN
it won't be necessary when this will be merged https://github.com/Joystream/pioneer/pull/3265

2022-06-30 12:42 UTC, merged