Ko-2770
Joystream/pioneer pull request #3274
Opened 2022-06-22 13:33 UTC by Ken-tech-max

fixed: 2770

2022-06-22 15:31 UTC, Ken-tech-max commented on packages/ui/src/memberships/components/MemberProfile/MemberProfile.tsx
> +type ProfileTabs = 'DETAILS' | 'ACCOUNTS' | 'Working Group Roles'
Alright I will change

2022-06-23 07:51 UTC, singulart requested changes

2022-06-23 07:51 UTC, singulart commented on packages/ui/src/proposals/components/ProposalDetails/renderers/Markdown/components/OpeningDescriptionPreview.tsx
> +            <SidePaneTitle>Signal Description</SidePaneTitle>
Please explain this change and it's purpose?

2022-06-23 07:51 UTC, singulart commented on packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/WorkingGroupLeadOpening/CreateWorkingGroupLeadOpening/StakingPolicyAndReward.tsx
> +  const maxAllowedForStakingAmount = 200
Please explain this change and it's purpose?

2022-06-23 07:51 UTC, singulart commented on packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/WorkingGroupLeadOpening/CreateWorkingGroupLeadOpening/StakingPolicyAndReward.tsx
> +            validation={stakingAmount < maxAllowedForStakingAmount ? 'invalid' : undefined}
Please explain this change and it's purpose?

2022-06-23 07:51 UTC, singulart commented on packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/WorkingGroupLeadOpening/CreateWorkingGroupLeadOpening/StakingPolicyAndReward.tsx
> +              maxAllowedValue={maxAllowedForStakingAmount}
Please explain this change and it's purpose?

2022-06-24 12:34 UTC, closed without merging