Search member by key (#2657)
Joystream/pioneer pull request #3289
Opened 2022-06-24 14:20 UTC by Funnydev1031

2022-06-24 14:27 UTC, singulart requested changes
"Search member by key" should become an additional feature on top what search can do already. What I see in your PR is that you have replaced the existing search behavior (search by handle) 

HINT: use logical "or" operator

2022-06-24 17:19 UTC, traumschule commented
Added a similar comment to the commit in https://github.com/Funnydev1031/pioneer-fork/commit/9d16071508bf1e14e9dc9ffc259354b58395ff9e before i realized the PR.

Pleace add to description:
- https://github.com/Joystream/pioneer/issues/2657
- https://github.com/Joystream/pioneer/issues/3253

2022-06-25 07:01 UTC, singulart requested changes

2022-06-25 07:01 UTC, singulart commented on packages/ui/src/memberships/hooks/useMembers.ts
> +  ...(search ? { OR: [{ controllerAccount_eq: search }, { handle_contains: search }] } : {}),
Please also include `rootAccount_eq`. Some users have same `rootAccount` and `controllerAccount`, but I saw many examples where users have them different. Thank you!

2022-06-27 20:08 UTC, singulart approved these changes

2022-07-01 08:26 UTC, RafalPloszka approved these changes

2022-07-01 08:55 UTC, merged