Feature/hide network behind the flag
Joystream/pioneer pull request #3340
Opened 2022-07-09 12:52 UTC by Palllke2015

Remove network name from the blockheight widget #3203

2022-07-10 19:08 UTC, WRadoslaw requested changes
Hello! Firstly thank you for your PR! I have 3 suggestions I'd like you to consider.

1. Let's keep changes from another PR strictly in that PR . Exepction from it would be situation where that changes are required to resolve issue that is taken on in second PR.
2. Please remeber to reqenerate queries when changes were made in any `.graphql` file. This is the script to do it -> `yarn run queries:generate`. 
3. Your solution is making network info kinda toggable (only from developer perspective, but still) and from the other side you are removing property of network from beeing fetched. Basically if you want to remove network from query, you have to go through each casting function and interface that posses that prop and make it optional, preferably remove it and resolve errors that will be caused by that action (that shouln't be many). 

Form the other side we can just remove the line with block string inside `BlockInfo` and do not bother about queries and interfaces, I'd consider it when there is possiblity in the future of utilizing `network` information in any other places. But that question should be addressed to @dmtrjsg.

2022-07-11 08:29 UTC, dmtrjsg commented
Discussed pros and cons of
 removing it from the component and keep fetching it in the meantime vs changing the queries to not fetch the network name.
 
Decision made to go with faster option so only change of component required.

2022-07-11 17:51 UTC, WRadoslaw commented on packages/ui/src/common/components/BlockTime/BlockInfo.tsx
> +    {!lessInfo && NETWORK_VISIBILITY && <BlockNetworkInfo>on {block.network} network</BlockNetworkInfo>}
```suggestion
    {/* <BlockNetworkInfo>on {block.network} network</BlockNetworkInfo> */}
```

Plus remove `NETWORK_VISIBILTY` and styled component

2022-07-11 21:09 UTC, WRadoslaw approved these changes

2022-07-11 21:09 UTC, merged