fix: Candiate bullet point in the voting modal
Joystream/pioneer pull request #3357
Opened 2022-07-14 13:39 UTC by gyroflaw

2022-07-15 00:04 UTC, freakstatic commented
LGTM!
@WRadoslaw could you please review?

2022-07-15 00:08 UTC, freakstatic commented
Fixes #2793

2022-07-15 09:35 UTC, WRadoslaw approved these changes
LGTM! Thanks 👏

2022-07-15 14:32 UTC, WRadoslaw requested changes
Realised that there is one thing that's need to be changed :D

2022-07-15 14:32 UTC, WRadoslaw commented on packages/ui/src/council/modals/VoteForCouncil/components/CandidacyReview.tsx
> +          <CandidacyPoint>{bulletPoint}</CandidacyPoint>
```suggestion
          <CandidacyPoint key={`${candidate.id}-bullet-${index}`}>{bulletPoint}</CandidacyPoint>
```

2022-07-18 13:08 UTC, WRadoslaw approved these changes

2022-07-18 13:40 UTC, merged

2022-07-19 09:52 UTC, dmtrjsg commented
@gyroflaw pls link with originating issue