Beard koda/reply to thread modal
Joystream/pioneer pull request #3451
Opened 2022-08-01 19:02 UTC by BeardKoda

- [ ] #3163
- [ ] ~~#2795~~

2022-08-02 07:11 UTC, singulart requested changes

2022-08-02 07:11 UTC, singulart commented on packages/ui/src/forum/components/PostList/PostListItem.tsx
> +    //   if (!active) showModal<SwitchMemberModalCall>({ modal: 'SwitchMember' })
Please remove commented out code

2022-08-02 07:11 UTC, singulart commented on packages/ui/src/forum/modals/PostActionModal/CreatePostModal/index.ts
> +    // isEditable: boolean
Please remove commented out code across your PR

2022-08-19 12:35 UTC, closed without merging

2022-08-22 07:26 UTC, thesan commented
We closed this PR because it had been idle for a long time, @BeardKoda please contact us or @singulart if you are still planning on updating it, in which case I will reopen it.