membership sort by name and show 5
Joystream/pioneer pull request #3575
Opened 2022-08-25 19:32 UTC by CoryITpro

This is for fixing https://github.com/Joystream/pioneer/issues/2334.
https://dao.joystream.org/#/bounty/preview/267

2022-08-26 08:37 UTC, freakstatic commented
LGTM!

2022-08-29 08:32 UTC, singulart commented
@CoryITpro Please address the failing checks.

2022-08-29 10:47 UTC, thesan requested changes
Hello @CoryITpro, thank you for your work. Please address the changes requested below.

2022-08-29 10:47 UTC, thesan commented on packages/ui/src/memberships/modals/SwitchMemberModal/SwitchMemberModal.tsx
> +      return members.filter((member) => modalData.membersToShow?.includes(member.id)).sort((a,b) => (a.handle > b.handle) ? 1 : ((b.handle > a.handle) ? -1 : 0))
The main problem with this way is that sorts uppercase char first, so `Z` comes before `a`. There is a `Comparator` function in `packages/ui/src/common/model/Comparator.ts` which should work well here:
```suggestion
      return members.filter((member) => modalData.membersToShow?.includes(member.id)).sort(Comparator(false, 'handle'))
```
(it just uses `string.localCompare(string)` under the hood)

2022-08-29 10:47 UTC, thesan commented on packages/ui/src/memberships/modals/SwitchMemberModal/SwitchMemberModal.tsx
> +    return members.sort((a,b) => (a.handle > b.handle) ? 1 : ((b.handle > a.handle) ? -1 : 0))
Same here:
```suggestion
    return members.sort(Comparator(false, 'handle'))
```

2022-09-02 21:46 UTC, CoryITpro commented
Completed

2022-09-05 07:45 UTC, singulart commented
Hi! @CoryITpro Can I ask why is this PR closed? From what I see in the comments, there were some improvements suggested by the reviewer. Have you had a chance to address them properly? In any case, you shouldn't have closed this PR before all comments are addressed..

2022-09-14 08:12 UTC, dmtrjsg commented
@CoryITpro get well soon buddy, let us know when you are back so we can resume work on this one..

2022-11-15 09:23 UTC, closed without merging