Feature/activity drawer
Joystream/pioneer pull request #3706
Opened 2022-10-17 14:44 UTC by WRadoslaw

2022-10-28 12:18 UTC, dmtrjsg commented
to be reviewed as the last one

2022-11-08 12:03 UTC, WRadoslaw commented
@thesan Ready for review

2022-11-08 15:23 UTC, thesan requested changes
Just a copy change

2022-11-08 15:23 UTC, thesan commented on packages/ui/src/app/pages/Forum/Forum.tsx
> +              Test
```suggestion
              Forum Activities
```

2022-11-14 17:23 UTC, thesan approved these changes
All good ! Just one more PR left to squash it all on `dev` :rocket: 
Sorry it looks like forgot about this one last Thursday :sweat:

2022-11-14 18:20 UTC, merged