Fix/filter lead
Joystream/pioneer pull request #3713
Opened 2022-10-18 16:52 UTC by traumschule

Filters lead form workers list (fixes #3704). The last two commits only differ in style, lmk which one you prefer and i'll squash.

This adds `isLead?` to the `WorkerBaseInfo` type and replaces `WorkerProps` in `Worker.tsx`. Please share if it turns out to affect anything else.

2022-10-24 12:07 UTC, WRadoslaw requested changes

2022-10-24 12:07 UTC, WRadoslaw commented on packages/ui/src/working-groups/components/WorkersList.tsx
>              {workers.map((worker, index) => (
Isn't it easier to just not render anything when the worker is a lead? Especially that `isLead` sounds like this component will render smth extra when the worker is a leader, not just omit it.

```suggestion
            {workers.map((worker, index) => worker.member.id !== lead?.meber.id && (
```
or just filter the results

```suggestion
            {workers.filter(worker => worker.member.id !== lead?.member.id).map((worker, index) => (
```

2022-10-25 07:41 UTC, WRadoslaw approved these changes

2022-10-28 22:14 UTC, traumschule commented
Shall i create a followup for the broken tests? Not sure how to fix the [timeout](https://github.com/Joystream/pioneer/actions/runs/3317806331/jobs/5481053207#step:7:636) on the fly.

2022-10-29 07:51 UTC, oleksanderkorn commented
> Shall i create a followup for the broken tests? Not sure how to fix the [timeout](https://github.com/Joystream/pioneer/actions/runs/3317806331/jobs/5481053207#step:7:636) on the fly.

Restarting tests usually helps, this looks like a flaky test. I had it before on my branches multiple times.

2022-11-02 18:33 UTC, merged