🤯 Execution consts validation for update wg budget
Joystream/pioneer pull request #3771
Opened 2022-10-28 13:16 UTC by WRadoslaw

2022-11-07 12:21 UTC, thesan requested changes

2022-11-07 12:21 UTC, thesan commented on packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/UpdateWorkingGroupBudget.tsx
> +      return new Date(Date.now() + blockToGo * MILLISECONDS_PER_BLOCK).getTime() - Date.now()
Isn't this just?
```suggestion
      return (Number(nextPaymentBlock) - currentBlock) * MILLISECONDS_PER_BLOCK
```

2022-11-07 12:21 UTC, thesan commented on packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/UpdateWorkingGroupBudget.tsx
> +  )
```suggestion
  const currentBlock = useCurrentBlockNumber()
```

2022-11-07 12:21 UTC, thesan commented on packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/UpdateWorkingGroupBudget.tsx
> +          {nextPaymentBlock && milisecondsLeft && (
Just to make sure to not render "0":
```suggestion
          {nextPaymentBlock && !!milisecondsLeft && (
```

2022-11-08 11:58 UTC, WRadoslaw commented on packages/ui/src/proposals/modals/AddNewProposal/components/SpecificParameters/UpdateWorkingGroupBudget.tsx
> +      return new Date(Date.now() + blockToGo * MILLISECONDS_PER_BLOCK).getTime() - Date.now()
Yes, it is :)

2022-11-17 18:55 UTC, thesan approved these changes
:100:

2022-11-17 19:53 UTC, merged