Eliminate `tJOY` and hide FM Banner
Joystream/pioneer pull request #3844
Opened 2022-11-15 18:00 UTC by traumschule

Fixes #3834

2022-12-02 01:27 UTC, freakstatic requested changes

2022-12-02 01:27 UTC, freakstatic commented on packages/ui/src/app/App.tsx
> +//import { FMBanner } from '@/app/components/FMBanner'
Same

2022-12-02 01:42 UTC, freakstatic reviewed
Shouldn't `FMBanner.tsx` be deleted?

2022-12-02 07:14 UTC, traumschule commented
ok boss :)

2022-12-03 18:42 UTC, freakstatic approved these changes

2022-12-06 09:01 UTC, thesan commented
@traumschule, @freakstatic sorry we completely missed this PR and the issue it was open to for. There is a different set of issues opened when Mainnet was planned and a another PR addressing them: #3859 which is already merged.

2022-12-06 09:01 UTC, closed without merging