Lead opening proposal whitelist limit (#2491)
Joystream/pioneer pull request #3861
Opened 2022-11-18 15:00 UTC by chrlschwb

Issue 2491.
When creating a WG lead opening, a whitelist limit of 20 was set, but the limit was not activated.
Created a new variable to implement this.
Error message "Maximum whitelist size of 20 members is reached." added.

2022-11-19 00:47 UTC, traumschule requested changes
This looks ok on itself but we need to follow the implemented logic. Marking this as draft. Would add to description: Fixes #2491 (follow-up to #3855)
cc @WRadoslaw

2022-11-19 00:47 UTC, traumschule commented on packages/ui/src/proposals/modals/AddNewProposal/components/TriggerAndDiscussionStep.tsx
> +    }
Please extend existing validation on the select field like [here](https://github.com/Joystream/pioneer/blob/dev/packages/ui/src/proposals/modals/AddNewProposal/components/TriggerAndDiscussionStep.tsx#L75), see also [machine.ts](https://github.com/Joystream/pioneer/blob/dev/packages/ui/src/proposals/modals/AddNewProposal/machine.ts)

2022-11-21 08:32 UTC, WRadoslaw requested changes
Hey! Thanks for your contribution! 

About the issue, I would prefer to keep validation strictly in the form vendor. Please check out `packages/ui/src/proposals/modals/AddNewProposal/helpers.ts` line `173` I suppose. The discussion whitelist is already validated there, so it's only about adding an additional method on `yup`. This may come in handy -> https://github.com/jquense/yup#array

2022-11-24 10:46 UTC, WRadoslaw requested changes

2022-11-24 10:46 UTC, WRadoslaw commented on packages/ui/src/proposals/modals/AddNewProposal/components/TriggerAndDiscussionStep.tsx
> -import React from 'react'
This file do not require any changes

2022-11-24 10:46 UTC, WRadoslaw commented on packages/ui/src/proposals/modals/AddNewProposal/helpers.ts
> +        is: Yup.array().length() < 20,
```suggestion
        is: true,
```

2022-11-24 10:46 UTC, WRadoslaw commented on packages/ui/src/proposals/modals/AddNewProposal/helpers.ts
>          then: Yup.array().required('Field is required'),
```suggestion
        then: Yup.array().max(20, 'Maximum whitelist size of ${max} members is reached.').required('Field is required'),
```

2022-12-15 14:40 UTC, chrlschwb commented on packages/ui/src/proposals/modals/AddNewProposal/helpers.ts
>          then: Yup.array().required('Field is required'),
changed accordingly

2022-12-17 01:58 UTC, traumschule commented
There's too much wrong here, please recreate after testing locally. @gyroflaw please help out with pioneer setup.
- deleted yarn.lock
- added node as dependency
- removed react from imports
- not using prettier
```
15:01:06.689 | \| src/utils.ts(11,22): error TS2769: No overload matches this call.
15:01:06.689 | \| Overload 1 of 2, '(o: {}): string[]', gave the following error.
15:01:06.689 | \| Argument of type 'T' is not assignable to parameter of type '{}'.
15:01:06.689 | \| Overload 2 of 2, '(o: object): string[]', gave the following error.
15:01:06.689 | \| Argument of type 'T' is not assignable to parameter of type 'object'.
15:01:06.717 | \| error Command failed with exit code 2.
```

2022-12-17 01:58 UTC, closed without merging