WG opening listing sorted in chronological order (#2513)
Joystream/pioneer pull request #3862
Opened 2022-11-18 15:16 UTC by chrlschwb

Issue #2513.
WG opening listings sorted in chronological order.

2022-11-19 01:04 UTC, traumschule requested changes
Draft for #2513

2022-11-19 01:04 UTC, traumschule commented on packages/ui/src/working-groups/hooks/useOpenings.ts
> +  const sortedOpenings= openings.slice().sort((a, b) => a.workingGroupOpening.updatedAt - b.workingGroupOpening.updatedAt)
This needs to happen on the [WorkingGroupsOpenings](https://github.com/Joystream/pioneer/blob/dev/packages/ui/src/app/pages/WorkingGroups/WorkingGroupsOpenings.tsx) page.  Also note the failing test:
```
ERROR in src/working-groups/hooks/useOpenings.ts:46:59
16:31:06.075 | \| TS2339: Property 'workingGroupOpening' does not exist on type 'WorkingGroupOpening'.
16:31:06.075 | \|     44 \|   )
16:31:06.075 | \|     45 \|
16:31:06.075 | \|   > 46 \|   const sortedOpenings= openings.slice().sort((a, b) => a.workingGroupOpening.updatedAt -
```

2022-11-19 19:53 UTC, traumschule commented on packages/ui/src/working-groups/hooks/useOpenings.ts
> +  const sortedOpenings= openings.slice().sort((a, b) => a.leadId - b.leadId)
please describe this change. looks like this would sort all openings by the `ID` of the lead membership vs chronologically.

2022-12-17 02:01 UTC, traumschule commented
Tests are failing. @gyroflaw do you think this is salvageable?

2023-02-19 19:36 UTC, traumschule commented
LGTM: https://dao-git-fork-chrlschwb-fix-2513-openingsorting-joystream.vercel.app/#/working-groups/openings
The design doesn't show creation time / block in the overview but it seems correct.

Why changes to 220 files? Still shows testnet banner - likely needs a rebase.

![openings-list](https://user-images.githubusercontent.com/31551045/219970994-87186ae9-153b-4a68-922f-77da1d28b383.png)

2023-02-20 03:04 UTC, chrlschwb commented
I'm closing this PR in favor of a new PR based on the most recent dev branch.
https://github.com/Joystream/pioneer/pull/4191

2023-02-20 03:04 UTC, closed without merging