Removed account info auto-fill from account selector (#2596)
Joystream/pioneer pull request #3880
Opened 2022-11-23 23:39 UTC by chrlschwb

Removed <AccountInfo> component from 
pioneer\packages\ui\src\accounts\components\SelectAccount\OptionAccount.tsx

2022-11-24 00:28 UTC, traumschule commented
#2596

2022-11-24 10:29 UTC, traumschule commented
This removed the account address. Positioning issue is unrelated.

![missing-address](https://user-images.githubusercontent.com/31551045/203760824-076e80c5-17f1-4224-8b9a-56b0f75adac2.png)

2022-12-09 15:26 UTC, traumschule requested changes

2022-12-09 15:26 UTC, traumschule commented on packages/ui/src/accounts/components/SelectAccount/OptionAccount.tsx
> +      {/*<AccountInfo account={option} locked={isLocked} />  // Address info commented out */}
This breaks account selection and does not fix the issue.

2022-12-13 22:15 UTC, oleksanderkorn requested changes
Worse to try `autocomplete="none"`:
<img width="841" alt="image" src="https://user-images.githubusercontent.com/9252017/207455850-df104363-5181-4931-80c0-0e7f54ace4ef.png">

Previous solution `autocomplete="new-password"` have been working but not anymore in the latest chrome.

There have been an ongoing discussion and this may still break in future versions:
https://stackoverflow.com/questions/15738259/disabling-chrome-autofill

2022-12-17 00:57 UTC, traumschule commented
I don't think this approach is the right solution. Feel free to reopen with a screenshot.

2022-12-17 00:57 UTC, closed without merging