Hide tooltip on locked accounts as soon as contents of scroll bar (accounts) start to get scrolled #3885
Joystream/pioneer pull request #3888
Opened 2022-11-24 22:14 UTC by oleksanderkorn

@WRadoslaw applied your suggestion, it is not flipping, but still not ideal, the tooltip link is hidden later than the tooltip itself, because of `transition: ${Transitions.all};`

2022-11-25 07:41 UTC, WRadoslaw commented
Yeah, unfortunately I have no idea why solution based on the popper API would suddenly stop working. About the scope, hiding tooltip on scroll won't change a thing, because this problem occurs when drop-down is totally static

2022-11-25 08:35 UTC, traumschule commented
GM! if i try to make it look back, the window manager helps by resizing the window without the UI catching a rerender.

![dropdown](https://user-images.githubusercontent.com/31551045/203936664-187f753b-a151-4b3a-beab-000039699dec.png)
![tooltip](https://user-images.githubusercontent.com/31551045/203936686-91747512-c483-4b73-abec-a0d521941d2c.png)

2022-12-12 16:52 UTC, thesan commented
@traumschule I think this only happen if the window size is reduced way passed what the app supports:
![](https://user-images.githubusercontent.com/31551045/203936686-91747512-c483-4b73-abec-a0d521941d2c.png)

@dmtrjsg, @oleksanderkorn but I'm not sure about what the issue is about... Here's what I'm getting on ff:
[Screencast from 2022-12-12 17-45-15.webm](https://user-images.githubusercontent.com/6571453/207104891-c981210a-1bda-4f6e-a7b6-4d91e9c0600b.webm)

Is this behavior wrong ?

2022-12-17 08:16 UTC, traumschule commented
It's not great :)

2023-02-14 17:34 UTC, thesan requested changes
This solution doesn't work for me ATM. The tooltips still scroll with the select options. I'll set this PR as a draft for now. I'll try to keep this in mind and add a suggestion later but rn I have no ideas.

@oleksanderkorn please update the PR if you think of something, but in the meantime I don't think this should be a priority.

cc @chrlschwb

2023-10-15 13:51 UTC, closed without merging