Create opening (#306)
Joystream/pioneer pull request #3891
Opened 2022-11-25 10:25 UTC by traumschule

According to #306

- [X] Add `Add Opening` button for lead to WG openings tab.
- [X] Open modal on click.
- [X] Import opening from json
- [X] Backup state to json
- [ ] Reuse steps with form state  and state machine from`CreateWorkingGroupLeadOpening`

Working on this one today, happy to incorporate your feedback.

2022-12-13 22:37 UTC, oleksanderkorn requested changes
LGTM, but i would say needs some cleanup.

2022-12-13 22:37 UTC, oleksanderkorn commented on packages/ui/src/working-groups/modals/CreateOpening/CreateOpening.tsx
> +  **/
Do we need this commented out block?

2022-12-13 22:37 UTC, oleksanderkorn commented on packages/ui/src/working-groups/modals/CreateOpening/components/Import.tsx
> +**/
Should this be cleaned up? :)

2022-12-13 22:37 UTC, oleksanderkorn commented on packages/ui/src/working-groups/modals/CreateOpening/machine.ts
> +              => SubmittableExtrinsic<ApiType>, [Bytes, PalletWorkingGroupOpeningType, PalletWorkingGroupStakePolicy, Option<u128>]>; **/
Same here, any reason of this being left?

2022-12-15 02:00 UTC, traumschule commented
Thanks! It also needs help with the state machine, not sure when i get to it. :(

2023-02-16 21:38 UTC, oleksanderkorn commented
As I can see in the last comment:

>@[dmtrjsg](https://github.com/dmtrjsg) dmtrjsg added this to Closed - On Prod in [Pioneer Community Product >Development](https://github.com/orgs/Joystream/projects/55#card-88069169) [2 days ago](https://github.com/Joystream/pioneer/pull/3891#event-8512582173)

@traumschule can we close this PR?

2023-02-19 18:47 UTC, traumschule commented
>  can we close this PR?

In my mind only if there's a merged fix for #306. I was hoping for support by someone to create a PR on top of this one.

2023-06-21 21:02 UTC, closed without merging