Set maximum WG budget increase amount (#2327)
Joystream/pioneer pull request #3920
Opened 2022-12-04 17:24 UTC by traumschule

#2327 

BN seems to have a limit of 10000000000000000.

2022-12-08 22:14 UTC, oleksanderkorn approved these changes
LGTM

2022-12-12 14:20 UTC, thesan requested changes
@traumschule here: ![https://github.com/Joystream/pioneer/issues/2327#issuecomment-1336443690](https://user-images.githubusercontent.com/31551045/205500259-3145f035-1c4b-42ae-a8bf-9b0c3af11ed7.png)

You identified a bug where a javascript number was passed to `asUpdateWorkingGroupBudget` instead of a `BN`, I'm not sure why the type system doesn't detect this, but it's probably because somehow the `fragment.amount` is typed `any`.

Here's an example of `BN` with values > $2^{53} – 1$ (`Number.MAX_SAFE_INTEGER`): https://codepen.io/thesan/pen/poKmpzb?editors=0012

That said on chain most amount are encoded as `u64` and currently the default  `maxAllowedValue` of `<TokenInput />` is `powerOf2(128)` so it should be changed to `powerOf2(64)`

2023-02-14 12:57 UTC, thesan requested changes

2023-02-19 18:00 UTC, traumschule commented on packages/ui/src/proposals/modals/AddNewProposal/helpers.ts
> +        .required('Field is required'),
```suggestion
      budgetUpdate: BNSchema.test(moreThanMixed(0, 'Amount must be greater than zero.')).required('Field is required'),
```

2025-12-03 13:59 UTC, traumschule commented
No longer needed.

2025-12-03 13:59 UTC, closed without merging