Fixed back link issue on opening with empty referrer
Joystream/pioneer pull request #3981
Opened 2022-12-14 11:14 UTC by vrrayz

Back button on openings now list to list page as requested from this https://github.com/Joystream/pioneer/issues/2977

2022-12-14 19:09 UTC, traumschule approved these changes
tested [here](https://github.com/Joystream/pioneer/pull/3798#pullrequestreview-1214906856)

2022-12-17 20:45 UTC, oleksanderkorn requested changes

2022-12-17 20:45 UTC, oleksanderkorn commented on packages/ui/src/common/components/page/PreviousPage.tsx
> +        <PreviousPageButton onClick={() => setPrevHistory(history, customLink!)} size="small" square>
I suggest to fix this by removing non null assertion and marking the customLink as nullable inside the method:
<img width="489" alt="image" src="https://user-images.githubusercontent.com/9252017/208265345-95057128-a7d6-42c9-b525-b6b7676e53e2.png">

<img width="639" alt="image" src="https://user-images.githubusercontent.com/9252017/208265401-611ab581-85cc-462a-957a-0398e8450154.png">

2022-12-17 20:45 UTC, oleksanderkorn commented on packages/ui/src/common/components/page/PreviousPage.tsx
> +        <PreviousPageButton onClick={() => setPrevHistory(history, customLink!)} size="small" square>
```suggestion
        <PreviousPageButton onClick={() => setPrevHistory(history, customLink)} size="small" square>
```

2022-12-20 09:37 UTC, thesan approved these changes
Thanks that's a great solution :raised_hands:

2022-12-20 09:37 UTC, merged