Fix icon on the Polkadot Block Explorer Menu item #3974
Joystream/pioneer pull request #3996
Opened 2022-12-24 15:26 UTC by vrrayz

Fixed Explorer Menu Item to match with the Figma Design from issue #3974

![Screenshot (441)](https://user-images.githubusercontent.com/33874323/209442537-897414a3-f026-42c4-a83b-4dcb875a7dff.png)

2022-12-24 18:45 UTC, traumschule reviewed
lgtm

2022-12-24 18:45 UTC, traumschule commented on packages/ui/src/common/components/icons/symbols/LinkSymbol.tsx
> +      {/* <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
if this solution is accepted the comment should be removed

2022-12-24 18:46 UTC, traumschule approved these changes

2023-01-02 11:12 UTC, oleksanderkorn requested changes
`LinkSymbol` is used in many more places, are you sure these changes will not break it anywhere?

Also i see commented code which should be either  uncommented or removed if not needed. 
Example of the usage in another place, which is now changed:
Before:
<img width="471" alt="image" src="https://user-images.githubusercontent.com/9252017/210223750-8ac0c355-f972-4f8d-9565-ebf00f9d3f40.png">
After:
<img width="439" alt="image" src="https://user-images.githubusercontent.com/9252017/210223821-c9faf733-2531-4586-8d2f-5bac46b0f7f5.png">

2023-01-04 23:31 UTC, vrrayz commented
> `LinkSymbol` is used in many more places, are you sure these changes will not break it anywhere?
> 
> Also i see commented code which should be either uncommented or removed if not needed. Example of the usage in another place, which is now changed: Before: <img alt="image" width="471" src="https://user-images.githubusercontent.com/9252017/210223750-8ac0c355-f972-4f8d-9565-ebf00f9d3f40.png"> After: <img alt="image" width="439" src="https://user-images.githubusercontent.com/9252017/210223821-c9faf733-2531-4586-8d2f-5bac46b0f7f5.png">

Thanks for the review., i'll check it and get back to you asap

2023-01-11 15:27 UTC, closed without merging

2023-01-11 15:36 UTC, vrrayz commented
Okay @oleksanderkorn and @traumschule , I have made the fix as suggested. please review again