Fix Rejected applicant is displayed as Pending
Joystream/pioneer pull request #4033
Opened 2023-01-07 15:21 UTC by gyroflaw

Fix https://github.com/Joystream/pioneer/issues/3856

2023-01-08 08:24 UTC, traumschule requested changes

2023-01-08 08:24 UTC, traumschule commented on packages/ui/src/working-groups/components/ApplicationsList.tsx
>          return 'Withdrawn'
This still hides "Withdrawn" (not hired) applicants: #3856

2023-01-12 11:54 UTC, ivanturlakov commented
Tested on https://dao-git-fork-gyroflaw-fix-application-status-joystream.vercel.app/#/working-groups/my-applications
wss://34.230.5.182.nip.io/ws-rpc

<img width="287" alt="Снимок экрана 2023-01-12 в 13 50 43" src="https://user-images.githubusercontent.com/46903215/212059699-2682add8-b1f4-4e04-bbe2-d8f4cf9e1fec.png">

### ✅ ivant-tester-ca
<img width="1181" alt="Снимок экрана 2023-01-12 в 13 51 09" src="https://user-images.githubusercontent.com/46903215/212059702-c3fecec2-0794-451e-8b04-b874676a2539.png">
<img width="540" alt="Снимок экрана 2023-01-12 в 13 51 24" src="https://user-images.githubusercontent.com/46903215/212059703-7a23e95a-e020-4ef3-acf0-efbb0bff5f07.png">

### ✅ ivant-tester-c
<img width="1181" alt="Снимок экрана 2023-01-12 в 13 53 00" src="https://user-images.githubusercontent.com/46903215/212060051-cb0f2eea-5cac-4816-a1d7-80c1295e4b6b.png">
<img width="540" alt="Снимок экрана 2023-01-12 в 13 53 08" src="https://user-images.githubusercontent.com/46903215/212060053-73b6b062-0432-42d6-8802-e6c422c2c25b.png">

@gyroflaw looks good 👍

2023-01-13 17:07 UTC, traumschule approved these changes
I hesitate to just approve this but likely a result of the runtime and out of scope.

In #4035 (storage-2) and [storage-3](https://dao-git-fork-gyroflaw-fix-application-status-joystream.vercel.app/#/working-groups/openings/storage-2) the application got automatically withdrawn when others were hired and as a result on the closed opening it now looks like `joystreamstats` never applied.

![applied](https://user-images.githubusercontent.com/31551045/212377355-396c3409-7283-4113-a27a-5a4520c55960.png)

![withdrawn](https://user-images.githubusercontent.com/31551045/212376285-4d310c94-ad31-4b0c-93bb-514ef87549dd.png)

2023-02-13 17:46 UTC, thesan approved these changes
LGTM!

2023-02-13 17:47 UTC, merged