Fix handle schema (#3263)
Joystream/pioneer pull request #4220
Opened 2023-03-10 15:32 UTC by traumschule

Fixes #3263

2023-03-13 04:01 UTC, chrlschwb approved these changes
ok, but there is a lint error

2023-03-13 12:15 UTC, traumschule commented
Tested locally: dot is allowed, space or slash are refused.

![nospace](https://user-images.githubusercontent.com/31551045/224698709-a762812b-6238-4edc-beb4-9a5269acf41e.png)
![space](https://user-images.githubusercontent.com/31551045/224698697-825188c3-cd04-430c-be6e-3f301bcf08c6.png)
![slash](https://user-images.githubusercontent.com/31551045/224698674-a5376bd4-2564-4529-8043-804cbc46d3b0.png)

2023-03-13 16:47 UTC, chrlschwb approved these changes

2023-03-14 08:31 UTC, thesan requested changes
Lets pause this PR until https://github.com/Joystream/pioneer/issues/3263#issuecomment-1329496200 can be reproduced consistently.

2023-03-14 10:59 UTC, closed without merging