Fix Election Blocktime Tooltip (#4156)
Joystream/pioneer pull request #4258
Opened 2023-03-23 13:23 UTC by chrlschwb

fixes issue #4156

2023-03-27 17:22 UTC, traumschule approved these changes
This changes the date into a link. It solves the tasks but i wonder if a block explorer link sympol like in the navigation would look better?
> Remove block tooltip
> Upon hover show block/date as clickable
> Upon click open block explorer in the new tab

before
![before](https://user-images.githubusercontent.com/93924525/218084048-4cd8c086-8f64-46f4-b89d-2c8ca6d54a9d.png)

after
![prophistory](https://user-images.githubusercontent.com/31551045/228017870-682db22e-694e-4eba-91c4-ef54429c1a67.png)

2023-03-30 08:33 UTC, thesan requested changes
Please use the [`BlockTime`](https://pioneer-2-storybook-joystream.vercel.app/?path=/story/common-blocktime--block-time-view) component instead. Like the way it shows on past elections:
![image](https://user-images.githubusercontent.com/6571453/228775506-b61bd1c4-2359-4c95-be24-dc9790a2928c.png)

Also you should remove `BlockHistoryLine` since it's only used here and on the [`stepper history story`](https://pioneer-2-storybook-joystream.vercel.app/?path=/story/common-stepper--history) where it can be replaced too.

2023-03-30 14:12 UTC, chrlschwb commented
Hello, @thesan. 
Removing the `BlockHistoryLine` wouldn't look good in my opinion.

2023-03-30 15:46 UTC, thesan commented
> Hello, @thesan. Removing the `BlockHistoryLine` wouldn't look good in my opinion.

@chrlschwb are you worried the `BlockTime` component would take to much space vertical space between the steps ?

2023-04-10 05:38 UTC, chrlschwb commented
@thesan 
By removing `BlockHistoryLine`, you mean to remove this?
![image](https://user-images.githubusercontent.com/101491745/230833780-3e02a887-7aef-4380-ba11-aaf95c08da12.png)

2023-04-14 09:07 UTC, thesan commented
@chrlschwb

No, I meant for each item to replace:

```
{stage}
{BlockHistoryLine}
```
By:

```
{stage}
{BlockTime}
```

With the variation of the `BlockTime` component being:

! [] (https://user-images.githubusercontent.com/6571453/228775506-b61bd1c4-2359-4c95-be24-dc9790a2928c.png) 

So each item will be 3 line instead of 2.

Of course there might still be some styling adjustment to make, so the components integrates well on this page.

2023-04-21 16:43 UTC, thesan requested changes

2023-04-21 16:43 UTC, thesan commented on packages/ui/src/common/components/BlockTime/BlockHistoryLine.tsx
> +export const BlockHistoryLine = ({ block }: BlockInfoProp) => {
@chrlschwb the ui looks good but is this component still necessary ? What happens if you just replace `details` in `@/proposals/components/ProposalHistory` by: `<BlockTime block={inBlock} layout="reverse-start" lessInfo />` ?

2023-04-21 16:43 UTC, thesan commented on packages/ui/src/common/components/BlockTime/BlockInfo.tsx
> -
Please remove the unnecessary changes to this file to prevent potential conflicts later on.

2023-10-25 14:12 UTC, thesan approved these changes

2023-10-25 19:33 UTC, merged

2023-10-27 16:34 UTC, polikosi commented
tested on: https://pioneer-2-git-fork-chrlschwb-fix-4156-removepa-bd4e07-joystream.vercel.app/

![image](https://github.com/Joystream/pioneer/assets/80429191/e8202c9d-1e5f-45b5-b6f6-6727e6a79a11)


Actual result: the [election page](https://pioneer-2-git-fork-chrlschwb-fix-4156-removepa-bd4e07-joystream.vercel.app/#/election/past-elections/0000000l) opens ater clicking.

Excpeted result: the block explorer should open in a new tab after clicking.