fixes #4256  Links don't wrap
Joystream/pioneer pull request #4296
Opened 2023-03-28 10:23 UTC by IlyaSmiyukha

- #4048

2023-03-28 10:36 UTC, IlyaSmiyukha commented
@chrlschwb Check pls

2023-03-29 12:10 UTC, chrlschwb approved these changes

2023-03-29 12:11 UTC, chrlschwb commented
Please contact me on discord. My discord handle: @Chaos77

2023-03-30 10:41 UTC, thesan requested changes
The issue only happens on Chrome. But this PR doesn't solve it for me:
![image](https://user-images.githubusercontent.com/6571453/228811428-1e2d8ec2-d6c2-4fcd-9784-863c3e769df5.png)

Tested on: https://dao-git-fork-ilyasmiyukha-4256-joystream.vercel.app/#/forum/thread/324

2023-03-30 10:59 UTC, IlyaSmiyukha commented
Missed fix for order list. Should be fine now

2023-03-30 11:33 UTC, thesan requested changes

2023-03-30 11:33 UTC, thesan commented on packages/ui/src/common/components/MarkdownPreview/MarkdownPreviewStyles.tsx
>      grid-row-gap: 8px;
Thank you! Sorry I didn't notice you had fixed it for `ul` only.

Just one small detail:
```suggestion
```

2023-03-30 13:25 UTC, thesan approved these changes
Perfect, thanks !

2023-03-30 15:09 UTC, merged