Fix Forum Loading Screen Text (#4102)
Joystream/pioneer pull request #4324
Opened 2023-04-05 09:33 UTC by chrlschwb

fixes issue #4102

2023-04-07 15:18 UTC, thesan requested changes
@chrlschwb adding the loader for the category is definitely an improvement. But similarly to https://github.com/Joystream/pioneer/pull/4318#pullrequestreview-1376297101 it doesn't deal with the consequence of the QN being unresponsive these days.

I think checking the error returned by the hook would allow to solve this issue.

[Peek 2023-04-07 17-11.webm](https://user-images.githubusercontent.com/6571453/230633586-8ff0cf5f-3848-4ec2-840a-3b3fe8514836.webm)

2023-04-11 13:52 UTC, traumschule approved these changes

2023-04-13 14:22 UTC, chrlschwb commented
I think [PR 4318](https://github.com/Joystream/pioneer/pull/4318) fixes issue #4102 as well.
The only change I added is "hasError"

2023-04-14 10:20 UTC, thesan requested changes

2023-04-14 10:20 UTC, thesan commented on packages/ui/src/app/pages/Forum/ForumCategory.tsx
> +    return <EmptyPagePlaceholder title="Something went wrong fetching this thread" copy="" button={null} />
```suggestion
    return <EmptyPagePlaceholder title="Something went wrong fetching this category." copy="" button={null} />
```

2023-04-21 16:19 UTC, thesan approved these changes
:+1:

2023-04-21 16:20 UTC, merged