Change Font color for visibility (#4094)
Joystream/pioneer pull request #4342
Opened 2023-04-10 16:01 UTC by chrlschwb

fixes issue #4094

2023-04-11 13:24 UTC, traumschule requested changes
LGTM, except

2023-04-11 13:24 UTC, traumschule commented on packages/markdown-editor/src/MarkdownEditor.js
> +
This change seems unnecessary.

2023-04-13 17:46 UTC, oleksanderkorn approved these changes

2023-04-14 10:03 UTC, thesan reviewed
@chrlschwb LGTM!

Just please ~~accept @oleksanderkorn suggestion~~ see comment :point_down:

2023-04-21 10:48 UTC, chrlschwb reviewed
delete empty line

2023-04-21 16:34 UTC, thesan approved these changes

2023-04-24 08:03 UTC, merged