Verified status: no visual representation in Pioneer UI
Joystream/pioneer pull request #4353
Opened 2023-04-17 02:37 UTC by AnttoLion

fixes #4300

2023-04-18 09:45 UTC, chrlschwb approved these changes
LGTM

2023-04-19 13:46 UTC, thesan requested changes
Good job, just one left over console log to remove please.

2023-04-19 13:46 UTC, thesan commented on packages/ui/src/memberships/components/MemberListFilters/MemberListFilters.tsx
> +      // console.log(action.field);
```suggestion
```

2023-04-20 08:35 UTC, thesan commented
@AnttoLion one more thing: the Gleev account shows when filtering verified accounts but doesn't have a tick mark. Could you check why please ? It's the only verified account I could find that isn't a FM too.

![image](https://user-images.githubusercontent.com/6571453/233308566-efe42403-1f05-4b47-9691-fc50ca3826b7.png)

2023-04-24 08:22 UTC, thesan requested changes
@AnttoLion it all looks good to me but the CI blocked the PR because apparently the code style of `VerifiedMemberIcon.tsx` and `useMembers.ts` don't fully follow the Prettier config. You can solve this by running `yarn lint:fix` (if it fails pull the `dev` branch because this script was fixed in the Ephesus release).

2023-04-26 10:17 UTC, thesan approved these changes
Perfect! Thank you :pray:

2023-04-26 10:19 UTC, merged

2023-04-26 12:54 UTC, AnttoLion commented
Thank you very much for all of your guidance @thesan.