#4232 signer modal component
Joystream/pioneer pull request #4362
Opened 2023-04-21 07:04 UTC by IlyaSmiyukha

closes #4232
@thesan @chrlschwb 
Check pls PR. I created a modal and stuck a bit with the backend. I'm not sure how properly connect the new API to the current frontend

2023-04-21 15:45 UTC, chrlschwb approved these changes
ok

2023-04-21 16:04 UTC, chrlschwb commented
For backend API this should help. 
https://github.com/Joystream/pioneer/pull/4210/files#diff-b097e1a2a6e98e4068893380ab22bb3bd17532e6108eb84d67630fd8485d952a

and this
https://www.apollographql.com/docs/react/data/mutations

2023-04-21 17:03 UTC, IlyaSmiyukha commented
Great, thanks. Will check it

2023-04-26 10:01 UTC, thesan requested changes
@IlyaSmiyukha great job creating the modal and the transaction flow, this can be painful write.

I have a few suggestion but most importantly this PR still needs to implement the BE mutation, please feel free to ask me on discord if you're stuck there.

Also please add a story for the `EmailSubscriptionModal`.

2023-05-31 11:11 UTC, thesan requested changes
@IlyaSmiyukha if I understand correctly you want to implement the backend mutation in a different PR. I think it's a good idea. You could also choose to implement the signature step in a different PR and just keep the "prepare" step and the "transaction" step (just an infinite `WaitModal` for now).

This feature is pretty complex feature so I think splitting it into 3 PRs makes sense. WDYT ?

2023-05-31 11:11 UTC, thesan commented on packages/ui/src/memberships/modals/EmailSubscriptionModal/EmailSubscriptionModal.tsx
> +
I think the sign modal can be triggered by simply calling:
```ts
const signature = await api.sign(member.controllerAccount, `${member.id}:${timestamp}`)
```

Keep in mind the `signup` mutation is:
```gql
signup(memberId: String! signature: String! timestamp: BigInt! name: String! email: String): String
```
(As documented in the [backend readme](https://github.com/Joystream/pioneer/tree/backend/packages/server#authentication)). So the signature and timestamp should be stored.

2023-06-01 09:18 UTC, thesan commented on packages/ui/src/memberships/modals/EmailSubscriptionModal/machine.ts
> +    },
@IlyaSmiyukha I just realized I had included (by mistake) a "CANCEL" action in the transaction step suggestion while I wrote that the "transaction" step couldn't be cancelled. So i now removed it.

However the signature step "CANCEL" is correct.

2023-06-13 11:14 UTC, thesan requested changes
@IlyaSmiyukha I just realized that this PR targets `dev` but it should target `backend`.

Please:
1. Retarget the PR (maybe you'll need to rebase the changes).
2. Address the change requests below.
3. Remove `@/memberships/modals/EmailSubscriptionModal/utils.ts`.

Then this PR can be merged, and you can implement the ` signature` step in a new PR.

2023-06-13 11:14 UTC, thesan commented on packages/ui/src/memberships/modals/EmailSubscriptionModal/machine.ts
> +}
I don't think this is relevant here

2023-06-13 11:14 UTC, thesan commented on packages/ui/src/memberships/modals/EmailSubscriptionModal/machine.ts
> +  form?: EmailSubscriptionForm
The context should include the email, the timestamp, and the signature

2023-06-22 11:57 UTC, closed without merging