Fix/4274 write nicer html emails #4274
Joystream/pioneer pull request #4410
Opened 2023-06-05 04:40 UTC by AnttoLion

2023-06-07 01:20 UTC, chrlschwb requested changes

2023-06-07 01:20 UTC, chrlschwb commented on packages/ui/src/app/pages/Proposals/EmailNotification.tsx
> +              <ContentBody>New proposal {'{proposal name}'} is created... there are 2 days left to vote...</ContentBody>
According to the issue https://github.com/Joystream/pioneer/issues/4274
you must create six variations of notifications. Please create the text of the contentbody and button as variables.

2023-06-13 08:01 UTC, chrlschwb reviewed
You must define "EmailNotifications.tsx" inside "src/common"

2023-07-04 09:45 UTC, thesan requested changes
@AnttoLion I don't know if this PR is still in progress, but in case it is:

Using React to generate html emails looks like a bad idea. Remember that the emails are generated on the backend so there shouldn't be any changes in `packages/ui/*`. Also you can't run js in emails and even though React can be used for ssr it's really not the right tool when the frontend can't run React.

2023-09-03 10:24 UTC, kdembler commented
@thesan This is superseded by my PR, can be closed

2023-09-08 10:02 UTC, thesan commented
Done in #4511

2023-09-08 10:02 UTC, closed without merging