Validators list page validator card
Joystream/pioneer pull request #4419
Opened 2023-06-09 05:15 UTC by eshark9312

Resolves #4327 
This PR is blocked by #4404 
Add Validator Card component

2023-06-14 20:54 UTC, chrlschwb approved these changes

2023-09-15 09:49 UTC, thesan commented
@chrlschwb this PR is not ready for review it includes a lot of changes from #4404 because git isn't able to differentiate identify them in the "squash and merge" commit (so they show as conflicts). @eshark9312 IMO you should `git rebase --onto dev validators-list-filter-search validators-list-page-validatorCard` but after you make sure that your local `dev` is at the latest version from `Joystream/pioneer`.

2023-11-24 16:57 UTC, thesan requested changes

2023-11-24 16:57 UTC, thesan commented on packages/ui/src/validators/modals/validatorCard/ValidatorDetail.tsx
> +            <SidePaneText>Alice1joystream.com</SidePaneText>
I think these sections (About, Email, Website, and all the other external resources) come from the membership bound to the validator account. 

Thus there is no need to re-implement these fields instead please re-use the code from Membership pane.

As a result I imagine this should be implemented after #4428 is merged.

2023-11-24 16:57 UTC, thesan commented on packages/ui/src/app/pages/Validators/ValidatorList.stories.tsx
> +                size: Math.floor(Math.random() * 2),
For this mock to work `withUnwrap` could be redefined like this:
```ts
const withUnwrap = (data: Record<any, any>) =>
  Object.defineProperties(data, {
    unwrap: { value: () => data },
    isSome: { value: Object.keys(data).length > 0 },
  })
```
This way defining an empty object would simulate a Nothing.

2023-11-24 16:57 UTC, thesan commented on packages/ui/src/validators/modals/validatorCard/ValidatorDetail.tsx
> +              <Stat size="s" value={validator.APR.toString()}>
This should have a `%` after it

2023-11-24 16:57 UTC, thesan commented on packages/ui/src/validators/modals/validatorCard/ValidatorDetail.tsx
> +              <Stat size="s" value={0}>
This too. Also do you know how to get this value ?

2023-11-24 16:57 UTC, thesan commented on packages/ui/src/validators/modals/validatorCard/ValidatorDetail.tsx
> +              <Stat size="s" value={20000}>
This should show as an amount of JOY (although its' not in the design) so it should use the `TokenValue` component somewhere (maybe you could use `TokenValueStat`.
Also do you know how to get this value ?

2023-11-24 16:57 UTC, thesan commented on packages/ui/src/validators/modals/validatorCard/ValidatorDetail.tsx
> +                <TextSmall lighter>Nominators</TextSmall>
In the design this is  "Staked by nominators":
![image](https://github.com/Joystream/pioneer/assets/6571453/d9b65464-c14c-4e8b-a710-cb966779484f)

And this should also show as an amount of JOY

2023-11-24 16:57 UTC, thesan commented on packages/ui/src/validators/modals/validatorCard/ValidatorDetail.tsx
> +              <Stat size="s" value={validator.slashed.toString()}>
This should have "times" or "time" at the end.

You could use:
```suggestion
              <Stat size="s" value={`${validator.slashed} time${plural(validator.slashed)}`}>
```

2023-11-24 17:01 UTC, thesan commented on packages/ui/src/validators/modals/validatorCard/ValidatorDetail.tsx
> +            <ModalStatistics>
Also please match the [design](https://www.figma.com/file/QnjZuWYtGimTEkQlN6MNlH/Validators?type=design&node-id=1799-410079&mode=design&t=CTRyskvdyi8y9VYk-0) order for the statistics.

![image](https://github.com/Joystream/pioneer/assets/6571453/cee8226a-3b73-4630-b76d-5a5b732f4d26)

2023-12-07 17:41 UTC, thesan commented
@eshark9312 `eshark9312:update-validators-list-columns` was merged into this branch [here](https://github.com/Joystream/pioneer/pull/4419/commits/7065554e9d651beaad3d7c601f31b5b9ed15fa27) has a result this PR now depends on #4643.

#4643 is almost ready, so as soon as it gets merged into `dev` please merge `dev` into this PR. It will make the review a lot easier.

2023-12-18 14:20 UTC, thesan requested changes

2023-12-18 14:20 UTC, thesan commented on packages/ui/src/mocks/helpers/asChainData.ts
> +    get: { value: (key: AccountId32) => data[encodeAddress(key.toString())] },
Good idea but just to make this a bit more general:
```suggestion
    get: {
      value: (key: unknow) => {
        switch (key) {
          case 'object':
            if (key.toRawType?.() === 'AccountId') {
              return data[encodeAddress(key.toString())]
            }
          default:
            return data[key.toString()]
        }
      }
    }
```

2023-12-19 09:23 UTC, thesan approved these changes
Great work! The graph looks good, I think we should go with `chart.js` instead of `nivo` for the financial dashboard too.

FYI all the nominate buttons will be changed into links to the the Polkadot app to nominate validators. But this should be done in a follow up PR. Also I don't remember what the copy should be.

2023-12-19 09:24 UTC, merged