restore insert table button
Joystream/pioneer pull request #4444
Opened 2023-06-17 17:54 UTC by traumschule

reviewing #4032 it looks like a mistake to remove the button

2023-06-17 18:25 UTC, traumschule reviewed
[successfully tested](https://dao-git-fork-traumschule-patch-18-joystream.vercel.app/#/forum/thread/47?post=3960)
![edittable](https://github.com/Joystream/pioneer/assets/31551045/85b7cbe9-a17f-4fda-ad8a-62295952fda7)

2023-06-19 10:26 UTC, thesan commented
@traumschule I'm confused, is this problem not happening anymore: https://github.com/Joystream/pioneer/issues/4032#issuecomment-1525939126 ?

2023-06-19 11:17 UTC, traumschule commented
it's fine for me.

2023-06-29 14:42 UTC, chrlschwb commented
@traumschule is the above screenshot the "preview" modal?
Preview mode works well for me as well, but the actual post displays like this.
https://dao-git-fork-traumschule-patch-18-joystream.vercel.app/#/forum/thread/460?post=4051

There is some conflict between the ckeditor plugin and the ReactMarkdown component.
Ckeditor uses HTML markdown, while the current setting uses GFM.

2023-09-01 14:36 UTC, thesan requested changes
This PR shouldn't get merged until this https://github.com/Joystream/pioneer/pull/4444#issuecomment-1613307131 gets fixed.

2025-12-03 19:08 UTC, traumschule commented
Closing in favor of #4935

2025-12-03 19:08 UTC, closed without merging