Fix/4379 member acount balance
Joystream/pioneer pull request #4450
Opened 2023-06-19 23:40 UTC by chrlschwb

fix #4379

2023-06-20 00:25 UTC, traumschule requested changes
@chrlschwb 
 | [warn] src/common/components/BlockTime/BlockHistoryLine.tsx
 | [warn] src/memberships/components/MemberProfile/MemberAccounts.tsx
 | [warn] Code style issues found in 2 files. Forgot to run Prettier?
 | `yarn lint` failed with exit code 1

@thesan wrt storybook:
> Error: No existing credentials found. Please run `vercel login` or pass "--token"

2023-06-20 00:40 UTC, traumschule commented on packages/ui/src/memberships/components/MemberProfile/MemberAccounts.tsx
> +          <TokenValue value={rootBalance?.total} isLoading={!isDefined(rootBalance?.total)} />
What could be the reason that it keeps blinking (never is defined)?

![blinking](https://github.com/Joystream/pioneer/assets/31551045/7420641f-8e36-4240-b3b6-38e809fa035e)

2023-07-31 14:25 UTC, HeinrichOlfert commented
![Uploading image.png…]()
I have error when run `yarn lint:fix`

2023-07-31 14:28 UTC, chrlschwb commented
![image](https://github.com/Joystream/pioneer/assets/101491745/6ef480a2-6862-48c1-a5f2-8d9cdf52ec3b)

I have error when run `yarn lint:fix`

2023-10-25 15:50 UTC, thesan commented
@chrlschwb please get reviews from BWG workers ideally 2 of them. It would really help the Pioneer review flow.

2023-11-13 09:37 UTC, kdembler requested changes
Left few comments. Also on visuals, I think the amount should be right-aligned, currently different values will be misaligned:
![CleanShot 2023-11-13 at 10 28 08@2x](https://github.com/Joystream/pioneer/assets/12646744/46717b1e-fe4b-4df8-af07-4233e6e5ddad)

2023-11-13 09:37 UTC, kdembler commented on packages/ui/src/common/modals/OnBoardingModal/OnBoardingPlugin.tsx
> +                <>
This fragment doesn't seem needed?

2023-11-13 09:37 UTC, kdembler commented on packages/ui/src/memberships/components/MemberProfile/MemberAccounts.tsx
> +export const AccountMemberRow = styled.div`
Why do we need to duplicate this style? We can use `AccountRow` as was imported before, and overwrite necessary CSS with `styled(AccountRow)`

2023-11-13 09:37 UTC, kdembler commented on packages/ui/src/memberships/components/MemberProfile/MemberBounds.tsx
> +        </AccountMemberRow>
This logic id duplicated 3 times: 1 one for root, 1 for controller and once in this component. I think we should adjust this component to be more generic and also use it for root and controller accounts

2023-11-15 13:16 UTC, kdembler commented
Hi @chrlschwb my last comment wasn't resolved. What I was suggesting was to make `MemberBounds` into something like this:
```tsx
export const MemberAccount = ({ account, name }: Props) => {
  const balance = useBalance(account)
  return (
    <div>
      {!!account && (
        <AccountMemberRow>
          <UnknownAccountInfo address={account} placeholderName={name} />
          <TokenValue value={balance?.total} isLoading={!isDefined(balance?.total)} />
        </AccountMemberRow>
      )}
    </div>
  )
}
```
Then you can use it for all accounts, like root:
```tsx
      {!!member.rootAccount && (
        <MemberAccount account={member.rootAccount} name="Root account" />
      )}
```
This way you can also move style next to this component, removing circular dependency between two files

2023-11-15 13:52 UTC, chrlschwb commented
> Hi @chrlschwb my last comment wasn't resolved. What I was suggesting was to make `MemberBounds` into something like this:
> 
> ```tsx
> export const MemberAccount = ({ account, name }: Props) => {
>   const balance = useBalance(account)
>   return (
>     <div>
>       {!!account && (
>         <AccountMemberRow>
>           <UnknownAccountInfo address={account} placeholderName={name} />
>           <TokenValue value={balance?.total} isLoading={!isDefined(balance?.total)} />
>         </AccountMemberRow>
>       )}
>     </div>
>   )
> }
> ```
> 
> Then you can use it for all accounts, like root:
> 
> ```tsx
>       {!!member.rootAccount && (
>         <MemberAccount account={member.rootAccount} name="Root account" />
>       )}
> ```
> 
> This way you can also move style next to this component, removing circular dependency between two files
year, I understand.

2023-11-15 13:52 UTC, chrlschwb commented
year I understand.

2023-11-15 14:18 UTC, kdembler approved these changes
Could you just update the `MemberBounds` component and file name now that it's generic? Otherwise, LGTM

2023-11-15 14:30 UTC, chrlschwb commented
what do you think the name?

2023-11-15 14:50 UTC, chrlschwb commented
> Could you just update the `MemberBounds` component and file name now that it's generic? Otherwise, LGTM ?

what?

2023-11-16 13:08 UTC, kdembler commented
I suggested `MemberAccount` earlier

2023-11-20 10:52 UTC, thesan approved these changes
Nice work, it looks great :+1:

2023-11-20 10:53 UTC, merged

2023-11-23 17:38 UTC, ivanturlakov commented
Tested on https://pioneer-2.vercel.app/#/profile/memberships
Mainnet

✅ Balance added
<img width="552" alt="Screenshot 2023-11-23 at 19 35 36" src="https://github.com/Joystream/pioneer/assets/46903215/a9faf473-4db9-4af9-a46c-a1f549ef3cff">