Fix/4526 changesiderbarexplorer
Joystream/pioneer pull request #4529
Opened 2023-09-06 17:34 UTC by chrlschwb

#4526 
![SUBSCAN](https://github.com/Joystream/pioneer/assets/101491745/a8349aed-16a7-46dd-a8dd-00f85fcbc459)
svg icon used for the link

2023-09-08 10:21 UTC, dmtrjsg commented
Looking good on the preview branch 👍

2023-09-08 13:19 UTC, thesan requested changes

2023-09-08 13:19 UTC, thesan commented on packages/ui/src/common/components/icons/symbols/ExplorerSymbol.tsx
> +  return (
Looks good but please use this version (it's optimized to reduce it's size):
```jsx
<svg width="26px" height="26px" viewBox="0 0 26 26" version="1.1" xmlns="http://www.w3.org/2000/svg">
  <g fill="currentColor">
    <path d="m13.8 3.21c0.733-0.733 0.733-1.92 0-2.66-0.733-0.733-1.92-0.733-2.66 0l-10.6 10.6c-0.733 0.733-0.733 1.92 0 2.66l5.31 5.31v2.08e-4c0.733 0.733 1.92 0.733 2.66 0l9.29-9.29 2.66 2.66-9.29 9.29c-0.733 0.733-0.733 1.92 0 2.66 0.733 0.733 1.92 0.733 2.66 0l10.6-10.6c0.733-0.733 0.733-1.92 0-2.66l-5.31-5.31c-0.733-0.733-1.92-0.733-2.66 0l-9.29 9.29-2.66-2.66 9.29-9.29z" opacity=".2"/>
    <path d="m3.21 11.2c0.733 0.733 0.733 1.92 0 2.66-0.733 0.734-1.92 0.734-2.66 0-0.733-0.733-0.733-1.92 0-2.66 0.733-0.734 1.92-0.734 2.66 0"/>
    <path d="m8.52 5.86c0.733 0.734 0.733 1.92 0 2.66-0.733 0.733-1.92 0.733-2.66 0-0.733-0.733-0.733-1.92 0-2.66 0.733-0.734 1.92-0.734 2.66-2.08e-4"/>
    <path d="m13.8 0.55c0.733 0.734 0.733 1.92 0 2.66-0.733 0.733-1.92 0.733-2.66 0-0.733-0.733-0.733-1.92 0-2.66 0.733-0.733 1.92-0.733 2.66 0"/>
    <path d="m8.52 16.5c0.733 0.733 0.733 1.92 0 2.66-0.733 0.733-1.92 0.733-2.66 0-0.733-0.733-0.733-1.92 0-2.66 0.733-0.733 1.92-0.733 2.66 0"/>
    <path d="m13.8 11.2c0.733 0.733 0.733 1.92 0 2.66-0.733 0.734-1.92 0.734-2.66 0-0.733-0.733-0.733-1.92 0-2.66 0.733-0.734 1.92-0.734 2.66 0"/>
    <path d="m19.1 5.86c0.733 0.734 0.733 1.92 0 2.66-0.733 0.733-1.92 0.733-2.66 0-0.733-0.733-0.733-1.92 0-2.66 0.733-0.734 1.92-0.734 2.66-2.08e-4"/>
    <path d="m13.8 21.8c0.733 0.733 0.733 1.92 0 2.66-0.733 0.733-1.92 0.733-2.66 0-0.733-0.733-0.733-1.92 0-2.66 0.733-0.733 1.92-0.733 2.66 0"/>
    <path d="m19.1 16.5c0.733 0.733 0.733 1.92 0 2.66-0.733 0.734-1.92 0.734-2.66 2.08e-4 -0.733-0.733-0.733-1.92 0-2.66 0.733-0.733 1.92-0.733 2.66 0"/>
    <path d="m24.5 11.2c0.733 0.733 0.733 1.92 0 2.66-0.733 0.734-1.92 0.734-2.66 0-0.733-0.733-0.733-1.92 0-2.66 0.733-0.734 1.92-0.734 2.66 0"/>
  </g>
</svg>
```

2023-09-08 13:19 UTC, thesan commented on packages/ui/src/common/components/icons/symbols/ExplorerSymbol.tsx
> +  return (
Also please rename the file to `SubscanSymbol.tsx`

2023-09-11 08:02 UTC, thesan approved these changes
Perfect thanks!

2023-09-11 08:03 UTC, merged