fix: past elections
Joystream/pioneer pull request #4565
Opened 2023-10-06 15:38 UTC by GoldWolf115

Fix past elections
- [USERSNAP] Past Elections: Total staked value does not include vote stakes #4090

2023-10-06 16:08 UTC, chrlschwb approved these changes
ok

2023-10-06 17:44 UTC, thesan requested changes
Thank you for the PR.

To fix the CI you should:
1. Fix the code linting by running: `yarn lint:fix`
2. Fix the interaction test by pulling the `dev` branch (because the storybook deployed from this branch is missing some new stories recently merged on `dev`).

2023-10-06 17:44 UTC, thesan commented on packages/ui/src/app/pages/Election/PastElections/PastElections.tsx
> +export const PastElectionsColLayout = '48px 100px 100px 100px 80px 80px'
There's enough space even on 1280px screen to keep the column headers on one line:
```suggestion
export const PastElectionsColLayout = '48px 176px 140px 140px 100px 100px'
```
![image](https://github.com/Joystream/pioneer/assets/6571453/e280c105-2694-4b82-ae29-9fdb4d4698d5)

2023-10-06 17:44 UTC, thesan commented on packages/ui/src/council/queries/__generated__/council.generated.tsx
> +  castVotes: Array<{ __typename: 'CastVote'; voteForId?: string | null; stake: string }>
You shouldn't update the generated files directly (ideally these shouldn't be tracked anymore).

Instead please edit `packages/ui/src/council/queries/council.graphql`, then run `yarn workspace @joystream/pioneer queries:generate`

2023-10-06 17:44 UTC, thesan commented on packages/ui/src/council/components/election/pastElection/PastElectionsList/PastElectionsListRow.tsx
>        <TokenValue value={election.totalStake} />
To clarify the code please rename this field:
```suggestion
      <TokenValue value={election.totalCandidatesStake} />
```

Here and in `packages/ui/src/council/types/PastElection.ts` too.

2023-10-09 16:24 UTC, thesan commented
@GoldWolf115 sorry I just realized that the interaction test failed earlier due to the GH workflow for new contributor (currently I should think of relaunching the storybook Vercel deployment before approving the GH CI run). However there's no harm in pulling the `dev` branch.

But now you need to rename `totalStake` to `totalCandidatesStake` in `@/council/components/election/pastElection/PastElectionTabs.tsx` because the Vercel deployments are failing ATM: https://vercel.com/joystream/dao/Hhx5dG8L4cyArcxMzjZzbMqz6Dxr?filter=all. To avoid these kind issues try to remember to check if the app is running locally with `yarn start` before pushing new commits.

2023-10-10 02:34 UTC, closed without merging