Rwd/sidebar and council
Joystream/pioneer pull request #4567
Opened 2023-10-09 08:12 UTC by eshark9312

2023-10-09 16:09 UTC, thesan requested changes
It's fine if you have already addressed this in further commits, but in case you haven't the past council pages (not the list but the page of a given past council) is not ready yet:

Header and statistics:
![image](https://github.com/Joystream/pioneer/assets/6571453/3220cd40-26b0-4d14-9a64-5c641430cc4a)

The "Go To Proposal" buttons (I think it's the `PastCouncilProposalsItem` component)
![image](https://github.com/Joystream/pioneer/assets/6571453/0eecb6fd-f5ec-448a-9d60-02a2cd5ec1c8)

2023-10-11 14:31 UTC, thesan requested changes
Great work! Just 3 small more comments. Also the member side panes are not usable yet but I think this should be addressed in some future PR.

2023-10-11 14:31 UTC, thesan commented on packages/ui/src/app/components/NavBar.tsx
> +const Wrapper = styled.div`
[The design](https://www.figma.com/file/EaObQEN95O0IWjSVTUQ5NN/Pioneer-RWD?type=design&node-id=706-202460&mode=dev) has a `box-shadow: 0px -1px 0px 0px rgba(187, 217, 246, 0.13) inset;` it's really subtle but I think it makes scrolling through white area better

2023-10-11 14:31 UTC, thesan commented on packages/ui/src/common/components/page/Sidebar/Navigation.tsx
>  export const NavigationInnerWrapper = styled.div`
Finally please reduce the height of the `barheader` row to `72px` on mobile to fully match [the sliding navigation design](https://www.figma.com/file/EaObQEN95O0IWjSVTUQ5NN/Pioneer-RWD?type=design&node-id=708-202748&mode=dev)

2023-10-13 15:36 UTC, thesan approved these changes
Once again great work :raised_hands: 

I just created a new branch called `responsive` and I re-targeted this PR to it. Once this PR is merged please pull this new branch on the changes you will create the next PR from (otherwise you can rebase part of your changes on it if you prefer).

2023-10-13 16:37 UTC, merged

2023-10-26 18:01 UTC, ivanturlakov commented
✅ Tested on https://dao-git-responsive-joystream.vercel.app/#/council
Mainnet

<img width="446" alt="Screenshot 2023-10-26 at 20 43 36" src="https://github.com/Joystream/pioneer/assets/46903215/31b5539d-79bd-4190-ae98-f6acf650d20a">
<img width="831" alt="Screenshot 2023-10-26 at 20 44 27" src="https://github.com/Joystream/pioneer/assets/46903215/2dbde1ed-8d28-4199-ad80-16cd126c6263">
<img width="794" alt="Screenshot 2023-10-26 at 20 45 36" src="https://github.com/Joystream/pioneer/assets/46903215/c9ba4d39-18df-4dc3-b5d2-b848083278e9">

2023-11-01 15:50 UTC, eshark9312 commented
@ivanturlakov 
I addressed this problem on the last [RWD PR](https://github.com/Joystream/pioneer/pull/4607), you can check [here](https://dao-38ivwh7by-joystream.vercel.app/).