fix/past-elections#4090 last
Joystream/pioneer pull request #4568
Opened 2023-10-10 03:34 UTC by GoldWolf115

2023-10-11 08:32 UTC, chrlschwb commented on packages/ui/.env.example
> +REACT_APP_IS_UNDER_MAINTENANCE=true
please uncommit changes to this file

2023-10-13 15:06 UTC, thesan commented
@chrlschwb please set `jsg-code-review` only after you have approved a PR

2023-10-16 01:08 UTC, chrlschwb requested changes

2023-10-16 01:08 UTC, chrlschwb commented on packages/ui/src/council/components/election/pastElection/PastElectionsList/PastElectionsListRow.tsx
> -
please uncommit this change

2023-10-16 01:08 UTC, chrlschwb commented on packages/ui/.env.example
> -REACT_APP_IS_UNDER_MAINTENANCE=true
please uncommit the deletion of this file

2023-10-16 07:27 UTC, closed without merging