fix/past-election#4090
Joystream/pioneer pull request #4578
Opened 2023-10-16 07:26 UTC by GoldWolf115

fix/past-election#4090

2023-10-16 07:35 UTC, chrlschwb approved these changes

2023-10-16 09:00 UTC, thesan requested changes
Just one change is needed :point_down: but please do not close PRs to reopen them as new ones. It makes the review process harder

2023-10-16 15:58 UTC, thesan approved these changes

2023-10-16 15:58 UTC, thesan commented on packages/ui/src/council/components/election/pastElection/PastElectionTabs.tsx
> +            totalStake: election.totalVoteStake,
Nice catch!

2023-10-24 09:02 UTC, merged

2023-10-27 15:49 UTC, polikosi commented
I left a comment here https://github.com/Joystream/pioneer/issues/4090#issuecomment-1781226950