Validator page responsiveness
Joystream/pioneer pull request #4706
Opened 2023-12-22 21:42 UTC by eshark9312

Added validator page to the sidebar menu.
Added responsiveness.

2023-12-29 10:55 UTC, thesan requested changes
The columns are really crammed together:
![image](https://github.com/Joystream/pioneer/assets/6571453/47ffc9b1-d93d-484f-a87f-b9795b5c1265)
There should be a gap on this grid.
And there should also be a gap after "Verification (?)":
![image](https://github.com/Joystream/pioneer/assets/6571453/3ad4da65-4252-420c-8957-78c672cb8b1c)

Also I noticed that it takes a while to get the validators. The list is loading for 20+ seconds. I'm assuming the rpc node is why the query is slow, but when I switch page the page loads again even though the provider should have the data already... Could you check what's going wrong please ?

2023-12-29 10:55 UTC, thesan commented on packages/ui/src/validators/modals/ValidatorsInfo.tsx
> +                ready to nominate, add the validators you'd like to nominate to by clicking the "Nominate" button on the
```suggestion
                ready to nominate, add the validators you'd like to nominate by clicking the "Nominate" button on the
```

2023-12-29 10:55 UTC, thesan commented on packages/ui/src/validators/modals/ValidatorsInfo.tsx
> +                list or directly on the validator’s profile. Once you've selected your validators, click the "Proceed"
```suggestion
                list or directly on the validator’s profile. Once you've selected a validator, click the "Proceed"
```

2023-12-29 10:55 UTC, thesan commented on packages/ui/src/validators/modals/ValidatorsInfo.tsx
> +import { Link } from 'react-router-dom'
```suggestion
import { Link } from '@/common/components/Link'
```

2023-12-29 10:55 UTC, thesan commented on packages/ui/src/validators/modals/ValidatorsInfo.tsx
> +              <Link to="#" style={{ color: Colors.Blue[500], textDecoration: 'underline' }}>
```suggestion
              <Link href="https://handbook.joystream.org/system/nomination">
```

2023-12-29 13:42 UTC, eshark9312 commented
@thesan 
The first loading takes 20+ seconds and the next time takes about 10s. That's due to `useValidatorsList` hook which fetches the detailed information for all validators. The `provider` only stores the validator addresses and memberships.
Do you want all data to be stored in the `provider` instead of `useValidatorsList` hook?

2023-12-29 13:59 UTC, thesan commented
> Do you want all data to be stored in the provider instead of useValidatorsList hook?

Yes I think it would be good. Just make sure the add validator modal doesn't fetch the extra data please.

2024-01-05 18:09 UTC, thesan approved these changes
Sorry for the delay on this PR I thought you were still working on it.

It looks good. I'll create a PR to speed up the page render and then the QA can start hopefully next week :crossed_fingers:.

This dashboard was tricky and the work wasn't well defined from the start but you did a great job. Thanks a lot :pray:

2024-01-05 18:10 UTC, merged