Open `OnBoardingModal` for modals requiring a membership
Joystream/pioneer pull request #4859
Opened 2024-07-02 15:00 UTC by hlvhe

Closes #4648

2024-07-07 18:16 UTC, thesan requested changes
Hi @hlvhe. Thank you for the contribution. This approach works as expected when no wallet is connected but when a wallet is connected but no membership is selected the switch membership still should show. The way I see it the "OnBoardingModal" should not replace the "SwitchMemberModal", the 2 cases should somehow be discriminated.

2024-07-29 07:47 UTC, thesan reviewed
Here's the flow when you don't have a wallet connected now:
[Screencast from 2024-07-29 09-31-44.webm](https://github.com/user-attachments/assets/0ffc5625-32c6-49c4-b538-178a95ad541b)

It's definitely an improvement compare to showing an empty membership switching modal. However the user still has to click the action once to pick a wallet then nothing happen until they click the action again.

Ideally they would:
1. pick there wallet
2. pick there membership
3. start the action they clicked on in the first place (e.g announce a candidacy)

To do this the "original modal" would have to be passed to the onboarding modal too, and this "original modal" should be handled there. Which might make the onboarding logic even more complex than it already is.

@kdembler WDYT ? Is this flow good enough for now ?

2024-07-31 12:04 UTC, kdembler commented
@thesan I can't get into details on this right now but if the PR behaviour is not ideal but still improves what we have currently, then that's good enough for me!

2024-08-10 14:13 UTC, thesan approved these changes

2024-08-10 14:13 UTC, merged