🧨 Set up activities logic
Joystream/pioneer pull request #651
Opened 2021-05-21 10:11 UTC by p-sad

Paving the way for #301 
This is a proof of concept for how activities could be represented in the application.

2021-05-21 10:19 UTC, p-sad commented on packages/ui/src/common/components/Activities/ActivityContent.tsx
> +      )
Might be worth wrapping these in separate components and returning only the extracted component, good/bad idea?

2021-05-21 13:29 UTC, jodator requested changes
@p-sad - just to change the PR state on GH. A short summary of a F2F review:

The activities component has a great potential to grow, so we need to prepare base activity components for an extension without modifying the component's code.

2021-05-24 09:24 UTC, jodator requested changes
Last small batch of changes before merge.

2021-05-24 09:24 UTC, jodator commented on packages/ui/src/common/components/Activities/ActivityContent.tsx
> +  }
Not great not terrible ;) Let's refactor that later when we have more activities from other modules.

2021-05-24 09:24 UTC, jodator commented on packages/ui/src/working-groups/types/WorkingGroupActivity.ts
> +  }
Let's start with `Pick<Member, 'id' | 'handle'>`.

2021-05-24 09:58 UTC, merged