Select member roles
Joystream/pioneer pull request #827
Opened 2021-06-11 15:26 UTC by thesan

Closes  #692

2021-06-11 15:36 UTC, thesan commented
It looks like #817 breaks the member filters box layout

2021-06-14 09:19 UTC, jodator requested changes
The component works very well :) I'd like to ask you only to add a test and move the z-index declaration to constant so we could have better z-index management.

2021-06-14 09:19 UTC, jodator commented on packages/ui/src/common/components/selects/SimpleSelect.tsx
> +  z-index: 51;
Let's put that to constants/styles.ts -> ZIndex variable

2021-06-14 09:19 UTC, jodator commented on packages/ui/src/common/utils.ts
>  export const objectEquals = <T extends Record<string, any>>(
This one would require a test. There's a lot going on and a test could clear up how it should be used.

2021-06-14 15:29 UTC, merged