Implement the Proposal Discussions thread
Joystream/pioneer pull request #986
Opened 2021-07-14 11:29 UTC by thesan

Just the thread part no editor

See #868 
See #801

2021-07-14 11:32 UTC, thesan commented
I realized there is still some work on "Allowing to mention someone" and "Post repay to selected message" on the editor so I will create another PR for that.

2021-07-15 10:11 UTC, jodator requested changes
Hey, overall nice progress with this :)

What's left:
- discussion mode [closed](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Design?node-id=2059%3A20)
  - closed should be grey
  - There should be info
- typo in the [reply to badge](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Design?node-id=2022%3A107529), should be: 'replied to ...'

2021-07-15 14:44 UTC, jodator requested changes
Almost 🙃

2021-07-15 14:44 UTC, jodator commented on packages/ui/src/proposals/components/ProposalDiscussions.tsx
> +            color: ${Colors.Black[75]};
background as well ;)

2021-07-15 14:56 UTC, jodator commented
@thesan The thread works nice :rocket: I've fixed the badge and I'm going to marge it after the CI.

2021-07-15 15:07 UTC, merged